export type CatalogWallet = {
  id: string;
  name: string;
  rdns: string[];
  href: string;
  icon: string;
  featured?: boolean;
  /** Reown AppKit wallet-button id. connect('okx') etc. */
  appkit?: string;
};

/**
 * Wallet catalog aligned with Reown AppKit’s Wallet Guide.
 * WalletConnect is not a wallet — it is opened via Reown AppKit, never as a GET/download tile.
 */
export const WALLET_CATALOG: CatalogWallet[] = [
  {
    id: "okx",
    name: "OKX Wallet",
    rdns: ["com.okex.wallet", "com.okx.wallet", "com.okx", "app.okx", "com.okex.okxwallet"],
    href: "https://web3.okx.com",
    icon: "/wallets/okx.svg",
    featured: true,
    appkit: "okx",
  },
  {
    id: "metamask",
    name: "MetaMask",
    rdns: ["io.metamask", "io.metamask.flask", "io.metamask.mobile"],
    href: "https://metamask.io/download",
    icon: "/wallets/metamask.svg",
    featured: true,
    appkit: "metamask",
  },
  {
    id: "trust",
    name: "Trust Wallet",
    rdns: ["com.trustwallet.app"],
    href: "https://trustwallet.com/download",
    icon: "/wallets/trust.svg",
    featured: true,
    appkit: "trust",
  },
  {
    id: "binance",
    name: "Binance Wallet",
    rdns: ["com.binance.wallet"],
    href: "https://www.binance.com/en/web3wallet",
    icon: "/wallets/binance.svg",
    featured: true,
    appkit: "binance",
  },
  {
    id: "bitget",
    name: "Bitget Wallet",
    rdns: ["com.bitget.web3", "com.bitget.wallet"],
    href: "https://web3.bitget.com/en/wallet-download",
    icon: "/wallets/bitget.svg",
    featured: true,
    appkit: "bitget",
  },
  {
    id: "coinbase",
    name: "Coinbase Wallet",
    rdns: ["com.coinbase.wallet"],
    href: "https://www.coinbase.com/wallet/downloads",
    icon: "/wallets/coinbase.svg",
    featured: true,
    appkit: "coinbase",
  },
  {
    id: "rabby",
    name: "Rabby",
    rdns: ["io.rabby"],
    href: "https://rabby.io",
    icon: "/wallets/rabby.svg",
    featured: true,
  },
  {
    id: "rainbow",
    name: "Rainbow",
    rdns: ["me.rainbow"],
    href: "https://rainbow.me/download",
    icon: "/wallets/rainbow.svg",
    featured: true,
    appkit: "rainbow",
  },
  {
    id: "phantom",
    name: "Phantom",
    rdns: ["app.phantom"],
    href: "https://phantom.com/download",
    icon: "/wallets/phantom.svg",
    appkit: "phantom",
  },
  {
    id: "tokenpocket",
    name: "TokenPocket",
    rdns: ["pro.tokenpocket"],
    href: "https://www.tokenpocket.pro/en/download/app",
    icon: "/wallets/tokenpocket.svg",
    appkit: "tokenpocket",
  },
  {
    id: "imtoken",
    name: "imToken",
    rdns: ["im.token.app"],
    href: "https://token.im/download",
    icon: "/wallets/imtoken.svg",
    appkit: "imtoken",
  },
  {
    id: "bybit",
    name: "Bybit Wallet",
    rdns: ["com.bybit"],
    href: "https://www.bybit.com/en/web3",
    icon: "/wallets/bybit.svg",
    appkit: "bybit",
  },
  {
    id: "uniswap",
    name: "Uniswap Wallet",
    rdns: ["org.uniswap.app"],
    href: "https://wallet.uniswap.org",
    icon: "/wallets/uniswap.svg",
    appkit: "uniswap",
  },
  {
    id: "zerion",
    name: "Zerion",
    rdns: ["io.zerion.wallet"],
    href: "https://zerion.io",
    icon: "/wallets/zerion.svg",
    appkit: "zerion",
  },
  {
    id: "safe",
    name: "Safe",
    rdns: ["app.safe.global"],
    href: "https://app.safe.global",
    icon: "/wallets/safe.svg",
    appkit: "safe",
  },
  {
    id: "ledger",
    name: "Ledger",
    rdns: ["com.ledger"],
    href: "https://www.ledger.com/ledger-live",
    icon: "/wallets/ledger.svg",
    appkit: "ledger",
  },
  {
    id: "safepal",
    name: "SafePal",
    rdns: ["io.safepal"],
    href: "https://www.safepal.com/download",
    icon: "/wallets/safepal.svg",
    appkit: "safepal",
  },
  {
    id: "oneinch",
    name: "1inch Wallet",
    rdns: ["io.oneinch.wallet"],
    href: "https://1inch.io/wallet",
    icon: "/wallets/oneinch.svg",
    appkit: "oneinch",
  },
  {
    id: "exodus",
    name: "Exodus",
    rdns: ["com.exodus.web3wallet", "app.exodus"],
    href: "https://www.exodus.com/download",
    icon: "/wallets/exodus.png",
    appkit: "exodus",
  },
  {
    id: "argent",
    name: "Ready (Argent)",
    rdns: ["app.ready", "argent.xyz"],
    href: "https://www.ready.co/download",
    icon: "/wallets/argent.svg",
    appkit: "argent",
  },
  {
    id: "brave",
    name: "Brave Wallet",
    rdns: ["com.brave.wallet"],
    href: "https://brave.com/wallet",
    icon: "/wallets/brave.svg",
    appkit: "brave",
  },
  {
    id: "kraken",
    name: "Kraken Wallet",
    rdns: ["com.kraken.wallet"],
    href: "https://www.kraken.com/wallet",
    icon: "/wallets/kraken.svg",
    appkit: "kraken",
  },
  {
    id: "cryptocom",
    name: "Crypto.com",
    rdns: ["com.crypto.wallet"],
    href: "https://crypto.com/eea/defi-wallet",
    icon: "/wallets/cryptocom.png",
    appkit: "crypto-com",
  },
  {
    id: "ronin",
    name: "Ronin",
    rdns: ["com.roninchain.wallet"],
    href: "https://wallet.roninchain.com",
    icon: "/wallets/ronin.svg",
    appkit: "ronin",
  },
  {
    id: "coin98",
    name: "Coin98",
    rdns: ["coin98.com"],
    href: "https://coin98.com/wallet",
    icon: "/wallets/coin98.svg",
    appkit: "coin98",
  },
  {
    id: "frame",
    name: "Frame",
    rdns: ["sh.frame"],
    href: "https://frame.sh",
    icon: "/wallets/frame.svg",
  },
  {
    id: "core",
    name: "Core",
    rdns: ["app.core.extension"],
    href: "https://core.app",
    icon: "/wallets/core.svg",
  },
  {
    id: "enkrypt",
    name: "Enkrypt",
    rdns: ["com.enkrypt.wallet"],
    href: "https://www.enkrypt.com",
    icon: "/wallets/enkrypt.svg",
  },
  {
    id: "taho",
    name: "Taho",
    rdns: ["xyz.taho"],
    href: "https://taho.xyz",
    icon: "/wallets/taho.svg",
  },
  {
    id: "onekey",
    name: "OneKey",
    rdns: ["so.onekey.app.wallet"],
    href: "https://onekey.so/download",
    icon: "/wallets/onekey.svg",
  },
  {
    id: "mew",
    name: "MEW Wallet",
    rdns: ["io.myetherwallet"],
    href: "https://www.myetherwallet.com/wallet/extension",
    icon: "/wallets/mew.svg",
  },
  {
    id: "subwallet",
    name: "SubWallet",
    rdns: ["app.subwallet"],
    href: "https://www.subwallet.app/download",
    icon: "/wallets/subwallet.svg",
  },
  {
    id: "frontier",
    name: "Frontier",
    rdns: ["com.frontier.wallet"],
    href: "https://www.frontier.xyz/download",
    icon: "/wallets/frontier.svg",
    appkit: "frontier",
  },
  {
    id: "gate",
    name: "Gate Wallet",
    rdns: ["io.gate.wallet"],
    href: "https://www.gate.io/web3",
    icon: "/wallets/gate.svg",
  },
  {
    id: "gemini",
    name: "Gemini Wallet",
    rdns: ["com.gemini.wallet"],
    href: "https://www.gemini.com/wallet",
    icon: "/wallets/gemini.svg",
  },
  {
    id: "ctrl",
    name: "Ctrl Wallet",
    rdns: ["xyz.ctrl"],
    href: "https://ctrl.xyz",
    icon: "/wallets/ctrl.svg",
  },
  {
    id: "fox",
    name: "FoxWallet",
    rdns: ["com.foxwallet"],
    href: "https://foxwallet.com",
    icon: "/wallets/fox.svg",
  },
  {
    id: "status",
    name: "Status",
    rdns: ["im.status.ethereum"],
    href: "https://status.app",
    icon: "/wallets/status.png",
    appkit: "status",
  },
  {
    id: "ambire",
    name: "Ambire",
    rdns: ["com.ambire.wallet"],
    href: "https://www.ambire.com",
    icon: "/wallets/ambire.png",
    appkit: "ambire-wallet",
  },
  {
    id: "valora",
    name: "Valora",
    rdns: ["co.valora.app"],
    href: "https://valora.xyz",
    icon: "/wallets/valora.svg",
    appkit: "valora",
  },
  {
    id: "zeal",
    name: "Zeal",
    rdns: ["app.zeal"],
    href: "https://www.zeal.app",
    icon: "/wallets/zeal.svg",
  },
  {
    id: "okto",
    name: "Okto",
    rdns: ["com.okto.wallet"],
    href: "https://okto.tech",
    icon: "/wallets/okto.svg",
  },
  {
    id: "backpack",
    name: "Backpack",
    rdns: ["app.backpack"],
    href: "https://backpack.app/download",
    icon: "/wallets/backpack.svg",
    appkit: "backpack",
  },
];

export const FEATURED_WALLETS = WALLET_CATALOG.filter((w) => w.featured);

export function matchCatalog(rdns: string): CatalogWallet | undefined {
  const key = rdns.toLowerCase();
  return WALLET_CATALOG.find((w) => w.rdns.includes(key));
}

/** @deprecated use matchCatalog */
export const matchFeatured = matchCatalog;
