/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AirdropRouteImport } from './routes/airdrop'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AriseRouteImport } from './routes/arise'
import { Route as BridgeRouteImport } from './routes/bridge'
import { Route as CapyaiRouteImport } from './routes/capyai'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as FundRouteImport } from './routes/fund'
import { Route as GovernanceRouteImport } from './routes/governance'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as HealthRouteImport } from './routes/health'
import { Route as LaunchRouteImport } from './routes/launch'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as ListRouteImport } from './routes/list'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MoveRouteImport } from './routes/move'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as StakingRouteImport } from './routes/staking'
import { Route as ZnzfRouteImport } from './routes/znzf'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiXPulseRouteImport } from './routes/api/x-pulse'
import { Route as AriseIndexRouteImport } from './routes/arise.index'
import { Route as AriseAiRouteImport } from './routes/arise.ai'
import { Route as AriseAirdropRouteImport } from './routes/arise.airdrop'
import { Route as AriseListingsRouteImport } from './routes/arise.listings'
import { Route as AriseMarketingRouteImport } from './routes/arise.marketing'
import { Route as AriseSettingsRouteImport } from './routes/arise.settings'
import { Route as AriseTokensRouteImport } from './routes/arise.tokens'
import { Route as AriseTreasuryRouteImport } from './routes/arise.treasury'
import { Route as AriseUsersRouteImport } from './routes/arise.users'
import { Route as CardsIdRouteImport } from './routes/cards.$id'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as DocsSlugRouteImport } from './routes/docs.$slug'
import { Route as TokenIdRouteImport } from './routes/token.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiXCallbackRouteImport } from './routes/api/x/callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AirdropRoute = AirdropRouteImport.update({
  id: '/airdrop',
  path: '/airdrop',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AriseRoute = AriseRouteImport.update({
  id: '/arise',
  path: '/arise',
  getParentRoute: () => rootRouteImport,
} as any)
const BridgeRoute = BridgeRouteImport.update({
  id: '/bridge',
  path: '/bridge',
  getParentRoute: () => rootRouteImport,
} as any)
const CapyaiRoute = CapyaiRouteImport.update({
  id: '/capyai',
  path: '/capyai',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const FundRoute = FundRouteImport.update({
  id: '/fund',
  path: '/fund',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernanceRoute = GovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchRoute = LaunchRouteImport.update({
  id: '/launch',
  path: '/launch',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const ListRoute = ListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MoveRoute = MoveRouteImport.update({
  id: '/move',
  path: '/move',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const StakingRoute = StakingRouteImport.update({
  id: '/staking',
  path: '/staking',
  getParentRoute: () => rootRouteImport,
} as any)
const ZnzfRoute = ZnzfRouteImport.update({
  id: '/znzf',
  path: '/znzf',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiXPulseRoute = ApiXPulseRouteImport.update({
  id: '/api/x-pulse',
  path: '/api/x-pulse',
  getParentRoute: () => rootRouteImport,
} as any)
const AriseIndexRoute = AriseIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AriseRoute,
} as any)
const AriseAiRoute = AriseAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AriseRoute,
} as any)
const AriseAirdropRoute = AriseAirdropRouteImport.update({
  id: '/airdrop',
  path: '/airdrop',
  getParentRoute: () => AriseRoute,
} as any)
const AriseListingsRoute = AriseListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => AriseRoute,
} as any)
const AriseMarketingRoute = AriseMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AriseRoute,
} as any)
const AriseSettingsRoute = AriseSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AriseRoute,
} as any)
const AriseTokensRoute = AriseTokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => AriseRoute,
} as any)
const AriseTreasuryRoute = AriseTreasuryRouteImport.update({
  id: '/treasury',
  path: '/treasury',
  getParentRoute: () => AriseRoute,
} as any)
const AriseUsersRoute = AriseUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AriseRoute,
} as any)
const CardsIdRoute = CardsIdRouteImport.update({
  id: '/cards/$id',
  path: '/cards/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsSlugRoute = DocsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DocsRoute,
} as any)
const TokenIdRoute = TokenIdRouteImport.update({
  id: '/token/$id',
  path: '/token/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiXCallbackRoute = ApiXCallbackRouteImport.update({
  id: '/api/x/callback',
  path: '/api/x/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/airdrop': typeof AirdropRoute
  '/analytics': typeof AnalyticsRoute
  '/arise': typeof AriseRouteWithChildren
  '/bridge': typeof BridgeRoute
  '/capyai': typeof CapyaiRoute
  '/docs': typeof DocsRouteWithChildren
  '/explore': typeof ExploreRoute
  '/fund': typeof FundRoute
  '/governance': typeof GovernanceRoute
  '/guide': typeof GuideRoute
  '/health': typeof HealthRoute
  '/launch': typeof LaunchRoute
  '/legal': typeof LegalRoute
  '/list': typeof ListRoute
  '/login': typeof LoginRoute
  '/move': typeof MoveRoute
  '/portfolio': typeof PortfolioRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/staking': typeof StakingRoute
  '/znzf': typeof ZnzfRoute
  '/api/health': typeof ApiHealthRoute
  '/api/x-pulse': typeof ApiXPulseRoute
  '/arise/ai': typeof AriseAiRoute
  '/arise/airdrop': typeof AriseAirdropRoute
  '/arise/listings': typeof AriseListingsRoute
  '/arise/marketing': typeof AriseMarketingRoute
  '/arise/settings': typeof AriseSettingsRoute
  '/arise/tokens': typeof AriseTokensRoute
  '/arise/treasury': typeof AriseTreasuryRoute
  '/arise/users': typeof AriseUsersRoute
  '/cards/$id': typeof CardsIdRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/token/$id': typeof TokenIdRoute
  '/arise/': typeof AriseIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/x/callback': typeof ApiXCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/airdrop': typeof AirdropRoute
  '/analytics': typeof AnalyticsRoute
  '/bridge': typeof BridgeRoute
  '/capyai': typeof CapyaiRoute
  '/explore': typeof ExploreRoute
  '/fund': typeof FundRoute
  '/governance': typeof GovernanceRoute
  '/guide': typeof GuideRoute
  '/health': typeof HealthRoute
  '/launch': typeof LaunchRoute
  '/legal': typeof LegalRoute
  '/list': typeof ListRoute
  '/login': typeof LoginRoute
  '/move': typeof MoveRoute
  '/portfolio': typeof PortfolioRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/staking': typeof StakingRoute
  '/znzf': typeof ZnzfRoute
  '/api/health': typeof ApiHealthRoute
  '/api/x-pulse': typeof ApiXPulseRoute
  '/arise/ai': typeof AriseAiRoute
  '/arise/airdrop': typeof AriseAirdropRoute
  '/arise/listings': typeof AriseListingsRoute
  '/arise/marketing': typeof AriseMarketingRoute
  '/arise/settings': typeof AriseSettingsRoute
  '/arise/tokens': typeof AriseTokensRoute
  '/arise/treasury': typeof AriseTreasuryRoute
  '/arise/users': typeof AriseUsersRoute
  '/cards/$id': typeof CardsIdRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/token/$id': typeof TokenIdRoute
  '/arise': typeof AriseIndexRoute
  '/docs': typeof DocsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/x/callback': typeof ApiXCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/airdrop': typeof AirdropRoute
  '/analytics': typeof AnalyticsRoute
  '/arise': typeof AriseRouteWithChildren
  '/bridge': typeof BridgeRoute
  '/capyai': typeof CapyaiRoute
  '/docs': typeof DocsRouteWithChildren
  '/explore': typeof ExploreRoute
  '/fund': typeof FundRoute
  '/governance': typeof GovernanceRoute
  '/guide': typeof GuideRoute
  '/health': typeof HealthRoute
  '/launch': typeof LaunchRoute
  '/legal': typeof LegalRoute
  '/list': typeof ListRoute
  '/login': typeof LoginRoute
  '/move': typeof MoveRoute
  '/portfolio': typeof PortfolioRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/staking': typeof StakingRoute
  '/znzf': typeof ZnzfRoute
  '/api/health': typeof ApiHealthRoute
  '/api/x-pulse': typeof ApiXPulseRoute
  '/arise/ai': typeof AriseAiRoute
  '/arise/airdrop': typeof AriseAirdropRoute
  '/arise/listings': typeof AriseListingsRoute
  '/arise/marketing': typeof AriseMarketingRoute
  '/arise/settings': typeof AriseSettingsRoute
  '/arise/tokens': typeof AriseTokensRoute
  '/arise/treasury': typeof AriseTreasuryRoute
  '/arise/users': typeof AriseUsersRoute
  '/cards/$id': typeof CardsIdRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/token/$id': typeof TokenIdRoute
  '/arise/': typeof AriseIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/x/callback': typeof ApiXCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/airdrop'
    | '/analytics'
    | '/arise'
    | '/bridge'
    | '/capyai'
    | '/docs'
    | '/explore'
    | '/fund'
    | '/governance'
    | '/guide'
    | '/health'
    | '/launch'
    | '/legal'
    | '/list'
    | '/login'
    | '/move'
    | '/portfolio'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/staking'
    | '/znzf'
    | '/api/health'
    | '/api/x-pulse'
    | '/arise/ai'
    | '/arise/airdrop'
    | '/arise/listings'
    | '/arise/marketing'
    | '/arise/settings'
    | '/arise/tokens'
    | '/arise/treasury'
    | '/arise/users'
    | '/cards/$id'
    | '/docs/$slug'
    | '/token/$id'
    | '/arise/'
    | '/docs/'
    | '/api/auth/$'
    | '/api/x/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/airdrop'
    | '/analytics'
    | '/bridge'
    | '/capyai'
    | '/explore'
    | '/fund'
    | '/governance'
    | '/guide'
    | '/health'
    | '/launch'
    | '/legal'
    | '/list'
    | '/login'
    | '/move'
    | '/portfolio'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/staking'
    | '/znzf'
    | '/api/health'
    | '/api/x-pulse'
    | '/arise/ai'
    | '/arise/airdrop'
    | '/arise/listings'
    | '/arise/marketing'
    | '/arise/settings'
    | '/arise/tokens'
    | '/arise/treasury'
    | '/arise/users'
    | '/cards/$id'
    | '/docs/$slug'
    | '/token/$id'
    | '/arise'
    | '/docs'
    | '/api/auth/$'
    | '/api/x/callback'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/airdrop'
    | '/analytics'
    | '/arise'
    | '/bridge'
    | '/capyai'
    | '/docs'
    | '/explore'
    | '/fund'
    | '/governance'
    | '/guide'
    | '/health'
    | '/launch'
    | '/legal'
    | '/list'
    | '/login'
    | '/move'
    | '/portfolio'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/staking'
    | '/znzf'
    | '/api/health'
    | '/api/x-pulse'
    | '/arise/ai'
    | '/arise/airdrop'
    | '/arise/listings'
    | '/arise/marketing'
    | '/arise/settings'
    | '/arise/tokens'
    | '/arise/treasury'
    | '/arise/users'
    | '/cards/$id'
    | '/docs/$slug'
    | '/token/$id'
    | '/arise/'
    | '/docs/'
    | '/api/auth/$'
    | '/api/x/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AirdropRoute: typeof AirdropRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AriseRoute: typeof AriseRouteWithChildren
  BridgeRoute: typeof BridgeRoute
  CapyaiRoute: typeof CapyaiRoute
  DocsRoute: typeof DocsRouteWithChildren
  ExploreRoute: typeof ExploreRoute
  FundRoute: typeof FundRoute
  GovernanceRoute: typeof GovernanceRoute
  GuideRoute: typeof GuideRoute
  HealthRoute: typeof HealthRoute
  LaunchRoute: typeof LaunchRoute
  LegalRoute: typeof LegalRoute
  ListRoute: typeof ListRoute
  LoginRoute: typeof LoginRoute
  MoveRoute: typeof MoveRoute
  PortfolioRoute: typeof PortfolioRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StakingRoute: typeof StakingRoute
  ZnzfRoute: typeof ZnzfRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiXPulseRoute: typeof ApiXPulseRoute
  CardsIdRoute: typeof CardsIdRoute
  TokenIdRoute: typeof TokenIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiXCallbackRoute: typeof ApiXCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/airdrop': {
      id: '/airdrop'
      path: '/airdrop'
      fullPath: '/airdrop'
      preLoaderRoute: typeof AirdropRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arise': {
      id: '/arise'
      path: '/arise'
      fullPath: '/arise'
      preLoaderRoute: typeof AriseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bridge': {
      id: '/bridge'
      path: '/bridge'
      fullPath: '/bridge'
      preLoaderRoute: typeof BridgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capyai': {
      id: '/capyai'
      path: '/capyai'
      fullPath: '/capyai'
      preLoaderRoute: typeof CapyaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fund': {
      id: '/fund'
      path: '/fund'
      fullPath: '/fund'
      preLoaderRoute: typeof FundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance': {
      id: '/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof GovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launch': {
      id: '/launch'
      path: '/launch'
      fullPath: '/launch'
      preLoaderRoute: typeof LaunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list': {
      id: '/list'
      path: '/list'
      fullPath: '/list'
      preLoaderRoute: typeof ListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/move': {
      id: '/move'
      path: '/move'
      fullPath: '/move'
      preLoaderRoute: typeof MoveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staking': {
      id: '/staking'
      path: '/staking'
      fullPath: '/staking'
      preLoaderRoute: typeof StakingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/znzf': {
      id: '/znzf'
      path: '/znzf'
      fullPath: '/znzf'
      preLoaderRoute: typeof ZnzfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/x-pulse': {
      id: '/api/x-pulse'
      path: '/api/x-pulse'
      fullPath: '/api/x-pulse'
      preLoaderRoute: typeof ApiXPulseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arise/': {
      id: '/arise/'
      path: '/'
      fullPath: '/arise/'
      preLoaderRoute: typeof AriseIndexRouteImport
      parentRoute: typeof AriseRoute
    }
    '/arise/ai': {
      id: '/arise/ai'
      path: '/ai'
      fullPath: '/arise/ai'
      preLoaderRoute: typeof AriseAiRouteImport
      parentRoute: typeof AriseRoute
    }
    '/arise/airdrop': {
      id: '/arise/airdrop'
      path: '/airdrop'
      fullPath: '/arise/airdrop'
      preLoaderRoute: typeof AriseAirdropRouteImport
      parentRoute: typeof AriseRoute
    }
    '/arise/listings': {
      id: '/arise/listings'
      path: '/listings'
      fullPath: '/arise/listings'
      preLoaderRoute: typeof AriseListingsRouteImport
      parentRoute: typeof AriseRoute
    }
    '/arise/marketing': {
      id: '/arise/marketing'
      path: '/marketing'
      fullPath: '/arise/marketing'
      preLoaderRoute: typeof AriseMarketingRouteImport
      parentRoute: typeof AriseRoute
    }
    '/arise/settings': {
      id: '/arise/settings'
      path: '/settings'
      fullPath: '/arise/settings'
      preLoaderRoute: typeof AriseSettingsRouteImport
      parentRoute: typeof AriseRoute
    }
    '/arise/tokens': {
      id: '/arise/tokens'
      path: '/tokens'
      fullPath: '/arise/tokens'
      preLoaderRoute: typeof AriseTokensRouteImport
      parentRoute: typeof AriseRoute
    }
    '/arise/treasury': {
      id: '/arise/treasury'
      path: '/treasury'
      fullPath: '/arise/treasury'
      preLoaderRoute: typeof AriseTreasuryRouteImport
      parentRoute: typeof AriseRoute
    }
    '/arise/users': {
      id: '/arise/users'
      path: '/users'
      fullPath: '/arise/users'
      preLoaderRoute: typeof AriseUsersRouteImport
      parentRoute: typeof AriseRoute
    }
    '/cards/$id': {
      id: '/cards/$id'
      path: '/cards/$id'
      fullPath: '/cards/$id'
      preLoaderRoute: typeof CardsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/$slug': {
      id: '/docs/$slug'
      path: '/$slug'
      fullPath: '/docs/$slug'
      preLoaderRoute: typeof DocsSlugRouteImport
      parentRoute: typeof DocsRoute
    }
    '/token/$id': {
      id: '/token/$id'
      path: '/token/$id'
      fullPath: '/token/$id'
      preLoaderRoute: typeof TokenIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/x/callback': {
      id: '/api/x/callback'
      path: '/api/x/callback'
      fullPath: '/api/x/callback'
      preLoaderRoute: typeof ApiXCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AriseRouteChildren {
  AriseAiRoute: typeof AriseAiRoute
  AriseAirdropRoute: typeof AriseAirdropRoute
  AriseListingsRoute: typeof AriseListingsRoute
  AriseMarketingRoute: typeof AriseMarketingRoute
  AriseSettingsRoute: typeof AriseSettingsRoute
  AriseTokensRoute: typeof AriseTokensRoute
  AriseTreasuryRoute: typeof AriseTreasuryRoute
  AriseUsersRoute: typeof AriseUsersRoute
  AriseIndexRoute: typeof AriseIndexRoute
}

const AriseRouteChildren: AriseRouteChildren = {
  AriseAiRoute: AriseAiRoute,
  AriseAirdropRoute: AriseAirdropRoute,
  AriseListingsRoute: AriseListingsRoute,
  AriseMarketingRoute: AriseMarketingRoute,
  AriseSettingsRoute: AriseSettingsRoute,
  AriseTokensRoute: AriseTokensRoute,
  AriseTreasuryRoute: AriseTreasuryRoute,
  AriseUsersRoute: AriseUsersRoute,
  AriseIndexRoute: AriseIndexRoute,
}

const AriseRouteWithChildren = AriseRoute._addFileChildren(AriseRouteChildren)

interface DocsRouteChildren {
  DocsSlugRoute: typeof DocsSlugRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsSlugRoute: DocsSlugRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AirdropRoute: AirdropRoute,
  AnalyticsRoute: AnalyticsRoute,
  AriseRoute: AriseRouteWithChildren,
  BridgeRoute: BridgeRoute,
  CapyaiRoute: CapyaiRoute,
  DocsRoute: DocsRouteWithChildren,
  ExploreRoute: ExploreRoute,
  FundRoute: FundRoute,
  GovernanceRoute: GovernanceRoute,
  GuideRoute: GuideRoute,
  HealthRoute: HealthRoute,
  LaunchRoute: LaunchRoute,
  LegalRoute: LegalRoute,
  ListRoute: ListRoute,
  LoginRoute: LoginRoute,
  MoveRoute: MoveRoute,
  PortfolioRoute: PortfolioRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StakingRoute: StakingRoute,
  ZnzfRoute: ZnzfRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiXPulseRoute: ApiXPulseRoute,
  CardsIdRoute: CardsIdRoute,
  TokenIdRoute: TokenIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiXCallbackRoute: ApiXCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
